name: "run tests"
on: "pull_request":
jobs:
  test_running:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: "setup"
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
        cache: 'pip'
        cache-dependency-path: |
          setup.*
          requirements*.txt
    - name: "install dependencies"
      run: "python -m pip install --upgrade pip"
    - name: "run tests"
      run: "pytest"
